apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
  annotations:
    # Optional: Make this the default so you don't have to specify it every time
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com   # <--- This uses your new EBS Add-on
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: gp3