name: Infra Destroy Pipeline

on:
  workflow_dispatch: 

env:
  REGION: ${{ vars.REGION }}

jobs:
  destroy-infra:
      runs-on: ubuntu-24.04
      needs: Infra-setup
      defaults:
        run:
          working-directory: Infra
      if: always()   # ensure destroy runs even if infra setup fails!
      steps:

        - name: checkout code from repo
          uses: actions/checkout@v4

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.REGION }}
            
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3

        - name: Terraform Init
          run: terraform init -input=false

        - name: Terraform Destroy
          run: terraform destroy -auto-approve -input=false